# Generated by Django 2.2.16 on 2020-10-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('ident', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='lav')),
            ],
        ),
        migrations.CreateModel(
            name='MisionyVision',
            fields=[
                ('ident', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('mision', models.TextField()),
                ('misionImg', models.ImageField(null=True, upload_to='lav')),
                ('vision', models.TextField()),
                ('visionImg', models.ImageField(null=True, upload_to='lav')),
                ('quienes', models.TextField()),
                ('quienesImg', models.ImageField(null=True, upload_to='lav')),
            ],
        ),
        migrations.CreateModel(
            name='SliderIndex',
            fields=[
                ('ident', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='lav')),
            ],
        ),
    ]
